# Generated by Django 4.2.8 on 2023-12-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cpf_cnpj', models.CharField(max_length=14, verbose_name='Nome Fantasia')),
                ('inscricao_estadual_RG', models.CharField(max_length=30, verbose_name='Inscrição Estadual/RG')),
                ('telefone', models.CharField(max_length=10, verbose_name='Telefone Fixo')),
                ('telefone_celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('contato', models.CharField(max_length=40, verbose_name='Contatos')),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Limite de Crédito')),
                ('numero_inteiro', models.IntegerField(verbose_name='Número qualquer')),
            ],
        ),
    ]
