# Generated by Django 4.2.8 on 2023-12-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='email',
            field=models.CharField(default='@', max_length=100, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
