# Generated by Django 4.2.8 on 2023-12-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_cadastro_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('referencia', models.CharField(max_length=14, verbose_name='EAN/GTIN')),
                ('unidade_medida', models.CharField(max_length=10, verbose_name='Unidade de Medida')),
            ],
        ),
    ]
