# Generated by Django 4.2.8 on 2023-12-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, verbose_name='CPF/CNPJ'),
        ),
    ]
